// Generated by CoffeeScript 1.3.3
(function() {
  var Boiler, path_, relativeModule, toDict,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  path_ = require('path');

  relativeModule = function(from, to) {
    return './' + path_.relative(path_.dirname(from), to).replace(/\\/g, '/');
  };

  toDict = function(kvps) {
    var dict, kvp, _i, _len;
    dict = {};
    for (_i = 0, _len = kvps.length; _i < _len; _i++) {
      kvp = kvps[_i];
      dict[kvp[0]] = kvp[1];
    }
    return dict;
  };

  Boiler = (function() {

    function Boiler() {
      this.debugging = false;
      this.filenameIdMap = {};
      this.id = 0;
      this.everything = '';
    }

    Boiler.prototype.require = function(file) {
      this.config = {
        exclude: [],
        path: ''
      };
      this.hookExtensions();
      require(path_.resolve(file));
      return this.unhookExtensions();
    };

    Boiler.prototype.filenameToId = function(filename) {
      if (!(filename in this.filenameIdMap)) {
        this.filenameIdMap[filename] = this.id += 1;
      }
      return this.filenameIdMap[filename];
    };

    Boiler.prototype.isExcluded = function(path, config) {
      if (config.excluded || __indexOf.call(config.exclude, path) >= 0) {
        return true;
      } else if (config.parent) {
        return this.isExcluded(path, config.parent);
      } else {
        return false;
      }
    };

    Boiler.injectScript = function(injects) {
      var alias, path;
      if (injects == null) {
        injects = {};
      }
      return ((function() {
        var _results;
        _results = [];
        for (alias in injects) {
          path = injects[alias];
          _results.push("var " + alias + "=require('" + path + "');\n");
        }
        return _results;
      })()).join('');
    };

    Boiler.exportScript = function(exp) {
      if (exp) {
        return "\n;module.exports=" + exp + ";";
      } else {
        return '';
      }
    };

    Boiler.requireWrap = function(content) {
      return "require = function(req) {\n  var require = function(path, opt) {\n    var res;\n    module.__boiler_hook_in(req.resolve, path, opt);\n    try {\n      res = req.call(this, path);\n    } catch (err) {\n      module.__boiler_hook_error(err);\n    } finally {\n      module.__boiler_hook_out();\n    }\n    return res;\n  };\n  for (var i in req) {\n    require[i] = req[i];\n  }\n  return require;\n}(require);\n" + content;
    };

    Boiler.boil = function(id, pathIdMap, code, filename) {
      return "register.call(this," + id + "," + (JSON.stringify(pathIdMap)) + ",\nfunction(require,exports,module){\n// file: " + (path_.relative(__dirname, filename)) + "\n" + code + "\n});";
    };

    Boiler.prototype.serve = function() {
      return "(function(everything){\n  window.boiler={main:{}};\n  var idModuleMap={};\n  function emulateRequire(pathIdMap){\n    function require(path, opt){\n      return idModuleMap[pathIdMap[path]];\n    }\n    return require;\n  }\n  function register(id,pathIdMap,factory){\n    var module={exports:{}};\n    factory.call(this,emulateRequire(pathIdMap),module.exports,module);\n    window.boiler.main=idModuleMap[id]=module.exports;\n  }\n  everything.call(this,register);\n}).call(this,function(register){\n" + this.everything + "\n});";
    };

    Boiler.prototype.unhookExtensions = function() {
      var ext, func, _ref, _results;
      _ref = require.extensions;
      _results = [];
      for (ext in _ref) {
        func = _ref[ext];
        if (func.__boiler_hook_orig != null) {
          _results.push(require.extensions[ext] = func.__boiler_hook_orig);
        }
      }
      return _results;
    };

    Boiler.prototype.hookExtensions = function() {
      var ext, func, _ref, _results,
        _this = this;
      _ref = require.extensions;
      _results = [];
      for (ext in _ref) {
        func = _ref[ext];
        if (!(func.__boiler_hook_orig != null)) {
          _results.push((function(ext, func) {
            var hook;
            hook = function(module, filename) {
              var cmp, codeBrowser, deps, fn, path, pathIdMap, that;
              that = _this;
              codeBrowser = '';
              deps = {};
              cmp = module._compile;
              module.__boiler_hook_in = function(resolve, path, opt) {
                var alias, fn, injects, p;
                if (opt == null) {
                  opt = {};
                }
                _this.debug("hook into " + path + ":" + filename);
                injects = toDict((function() {
                  var _ref1, _results1;
                  _ref1 = opt.injects || {};
                  _results1 = [];
                  for (alias in _ref1) {
                    p = _ref1[alias];
                    fn = relativeModule(resolve(path), resolve(p));
                    _results1.push([alias, fn]);
                  }
                  return _results1;
                })());
                _this.config = {
                  parent: _this.config,
                  exclude: opt.exclude || [],
                  excluded: opt.excluded || _this.isExcluded(path, _this.config),
                  exports: opt.exports,
                  injects: injects,
                  path: path
                };
                deps[path] = resolve(path);
                return _this.debug(_this.config);
              };
              module.__boiler_hook_error = function(err) {
                return _this.debug("hook error " + _this.config.path + ":" + filename + ": " + err);
              };
              module.__boiler_hook_out = function() {
                _this.debug("hook outof " + _this.config.path + ":" + filename);
                if (_this.config.parent) {
                  return _this.config = _this.config.parent;
                }
              };
              module._compile = function(content, filename) {
                var code, codeNode;
                code = Boiler.injectScript(that.config.injects) + content;
                codeBrowser = code + Boiler.exportScript(that.config.exports);
                codeNode = Boiler.requireWrap(code);
                return cmp.call(this, codeNode, filename);
              };
              try {
                func(module, filename);
              } catch (err) {
                _this.debug("error: " + err);
              }
              if (!_this.config.excluded) {
                _this.debug("boiling " + _this.config.path + ":" + filename);
                pathIdMap = toDict((function() {
                  var _results1;
                  _results1 = [];
                  for (path in deps) {
                    fn = deps[path];
                    _results1.push([path, this.filenameToId(fn)]);
                  }
                  return _results1;
                }).call(_this));
                _this.everything += Boiler.boil(_this.filenameToId(filename), pathIdMap, codeBrowser, filename);
              } else {
                _this.debug('excluded ' + filename);
              }
              return _this.hookExtensions();
            };
            hook.__boiler_hook_orig = func;
            return require.extensions[ext] = hook;
          })(ext, func));
        }
      }
      return _results;
    };

    Boiler.prototype.debug = function() {
      if (this.debugging) {
        return console.log.apply(this, arguments);
      }
    };

    return Boiler;

  })();

  module.exports = function(file, debug) {
    var boiler;
    if (debug == null) {
      debug = false;
    }
    boiler = new Boiler;
    boiler.debugging = debug;
    boiler.require(file);
    if (debug) {
      return '';
    } else {
      return boiler.serve();
    }
  };

  module.exports.Boiler = Boiler;

}).call(this);
